worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/stderr info;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80 default_server;
        server_name _;
        location / {
            default_type application/json;
            return 200 '{"service":"portwyrm","status":"bootstrap"}';
        }
    }

    include /data/nginx/*.conf;
}
