"""Nginx platform and shared include rendering."""

from __future__ import annotations

from .nginx_models import PlatformConfig


def render_main(platform: PlatformConfig) -> str:
    resolver = ""
    if platform.resolver_enabled:
        resolver = f"  resolver {' '.join(platform.resolver_addresses)} valid=30s;\n"
    return (
        "# Generated by Portwyrm\n"
        "load_module /usr/lib/nginx/modules/ngx_stream_module.so;\n"
        "worker_processes auto;\n"
        "pid /tmp/nginx.pid;\n"
        "error_log /dev/stderr info;\n"
        "include custom/root_top.conf;\n"
        "events { worker_connections 1024; include custom/events.conf; }\n"
        "http {\n"
        "  include /etc/nginx/mime.types;\n"
        "  default_type application/octet-stream;\n"
        "  log_format proxy '$remote_addr - $host [$time_local] $request $status "
        "$body_bytes_sent';\n"
        "  include custom/http_top.conf;\n"
        "  proxy_cache_path /var/lib/nginx/cache/public levels=1:2 "
        "keys_zone=public-cache:30m max_size=192m;\n"
        f"{resolver}"
        "  include include/trusted-proxies.conf;\n"
        "  include http/*.conf;\n"
        "  include custom/http.conf;\n"
        "}\n"
        "stream { log_format stream '$remote_addr [$time_local] $protocol $status'; "
        "include stream/*.conf; include custom/stream.conf; }\n"
        "include custom/root.conf;\n"
    )


def render_status_site() -> str:
    return (
        "# Loopback-only operational telemetry for the Portwyrm control plane\n"
        "server {\n"
        "  listen 127.0.0.1:8081;\n"
        "  server_name _;\n"
        "  access_log off;\n"
        "  location = /nginx-status {\n"
        "    stub_status;\n"
        "    allow 127.0.0.1;\n"
        "    deny all;\n"
        "  }\n"
        "}\n"
    )


def render_proxy_include() -> str:
    return (
        "proxy_set_header Host $host;\n"
        "proxy_set_header X-Real-IP $remote_addr;\n"
        "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
        "proxy_set_header X-Forwarded-Proto $scheme;\n"
        "proxy_pass $forward_scheme://$server:$port;\n"
    )


def render_block_exploits() -> str:
    return "location ~* /(?:\\.git|\\.env|wp-config\\.php) { deny all; }\n"


def render_trusted_proxies(platform: PlatformConfig) -> str:
    lines = ["# Trusted reverse-proxy ranges"]
    for address in sorted(platform.trusted_proxy_ranges):
        lines.append(f"set_real_ip_from {address};")
    if platform.trusted_proxy_ranges:
        lines.extend(["real_ip_header X-Forwarded-For;", "real_ip_recursive on;"])
    return "\n".join(lines) + "\n"


def render_default_site(platform: PlatformConfig) -> str:
    mode = platform.default_site
    if mode == "congratulations":
        body = 'return 200 "Congratulations! Portwyrm is running.\\n";'
    elif mode in {"404", "444"}:
        body = f"return {mode};"
    elif mode == "redirect":
        body = f"return 301 {platform.default_redirect};"
    else:
        body = "root /data/nginx/default_www;\n    try_files $uri /index.html;"
    ipv6 = "  listen [::]:80 default_server;\n" if platform.ipv6 else ""
    return (
        "server {\n"
        "  listen 80 default_server;\n"
        f"{ipv6}"
        "  server_name _;\n"
        "  location ^~ /.well-known/acme-challenge/ {\n"
        "    root /data/acme-challenge;\n"
        "    try_files $uri =404;\n"
        "  }\n"
        "  location / {\n"
        f"    {body}\n"
        "  }\n"
        "}\n"
    )


__all__ = [
    "render_block_exploits",
    "render_default_site",
    "render_main",
    "render_proxy_include",
    "render_status_site",
    "render_trusted_proxies",
]
